### ISSUE TITLE
Hard-wired English language strings.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kennibc/moodle-theme_evolved#10]
Hi,
When I use the evolve-D theme with the socialwall format for Moodle 2.8.6, there are a few Hard-wired English language strings shown:

![hard-wired english strings in evolve-d theme](https://cloud.githubusercontent.com/assets/2671923/8991074/c7409912-36bb-11e5-9d38-c521c370bc41.png)

I had originally thought this to be an issue related to the socialwall format, but it only shows when I use the evolve-D theme. Please see https://github.com/synergylearning/moodle-format_socialwall/issues/4

Thanks in advance for your help and for writing these two great plugins for Moodle.

**Comment by kennibc** [comment]
Those are indeed part of the CSS.  They are used in a content string in the CSS starting around line 766 of the evolved.css file.

You can easily change the text.  Or if you want to help I don't know how to use a language string in CSS.

.format-socialwall ul.section.tl-postattachment:before {
  content: "\f0c6  Attachments";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  margin-left:-15px;
  padding-bottom: 4px;
  border-bottom:2px solid #ccc;
}
.format-socialwall .tl-comments:before {
  content: "\f0e6  Comments";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  padding-bottom: 4px;
  width:100%;
  text-align: center;
}

.format-socialwall .tl-posttext:before{
  content: "\f0e5  Message";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  padding-bottom: 4px;
  border-bottom:2px solid #ccc;
  width:100%;
  text-align: center;
}

.format-socialwall .tl-post:before{
  content: "\f086  Post";
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 18px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  padding-bottom: 4px;
  padding-left:15px;
  text-align: center;
}

**Comment by lazydaisy** [comment]
My goodness me! Language strings are not part of CSS, if they exist you should coded where they need to be seen on the page using PHP get_string('post', 'theme_evolved') and add them to your theme lang/en/theme_evolved.php as a language string:
$string['post'] = 'Post';
Please DO NOT HARD CODE THEM!!!
Cheers
Mary

**Comment by kennibc** [comment]
Well Mary, how about showing me how to fix it instead of yelling at me.  I am not a programmer but I am willing to learn but not like this.   One of the spots that needs help is here:  https://github.com/kennibc/moodle-theme_evolved/blob/master/style/evolved.css#L796  

Show me how to do one and I can handle the rest.

**Comment by lazydaisy** [comment]
That's not yelling...
What you need to do is perhaps read the online php manual about how to code.
That is how I learned.
The key to this problem lies in the Social Forum php which would entail perhaps seeing if there was a renderer that you could customised?
I will need to see the php where the forum is generated.

**Comment by lazydaisy** [comment]
It's too late now and I am suffering from a back injury and in some pain.

**Comment by lazydaisy** [comment]
Now this is where things can get confusing. You say you are not a programmer yet your name is listed as been part of a team building/maintaining the SocialWall course format.
To be able to do things correctly you need to either add some new functionality to the existing SocialWall course format plugin, or create a new course formal plugin based on the existing one. Perhaps call it SocialWallEvolved-D.
Then you can add the get_strings into the parts of the forum areas that need them.
If you do not know how to do this then ask Gareth as he has lots of Course Format building experience.

**Comment by kennibc** [comment]
I am listed as a developer because I was part of a team who made this plugin happen for the Moodle community.  We contracted out development with Synergy Learning who actually are working on the next release right now.  The new version with some killer features should be out in late august or september.  

As for this issue I do not like the idea of splitting Socialwall.  I'll just remove this styling effect from the evolve-D theme and keep it for ourselves.  It is not that big of a deal just to have the words Post, Comments, and Attachments appear in the social feed.  To add that in by splitting Socialwall development or having a new version would be too much for something so trivial.

**Comment by kennibc** [comment]
@germanvaleroelizondo If you need this removed you simply have to remove the snippet of code mentioned above.  Done and gone.  It shouldn't effect anything else.

**Comment by germanvaleroelizondo** [comment]
@kennibc I am sorry things went that way. I only wanted this very nice and very popular plugin to be 100% available for translators. I will write today a small Moodle Docs text documenting how to do the changes in the code you described, for anyone who would like to have these few words translated into another language.

Thanks again for having helped to make this very nice plugin available for so many Moodlers worldwide.

I am not a programmer either. I am a veterinarian working for a Mexican University.

**Comment by germanvaleroelizondo** [comment]
@kennibc I had just written the Moodle Docs page at https://docs.moodle.org/29/en/evolve-D_theme with step-by-step detailed instructions with screendumps about how to customize these hard-wired strings. I will soon write the Spanish translation for this page.

Please do not remove the hard-wired strings from the existing code, as users now have very easy-to-follow instructions for having this great plugin fully translated into their language of choice :)

**Comment by lazydaisy** [comment]
@kennibc 

Meeting you halfway, might I suggest you add the bodyclass to your CSS for some popular languages, which over time could be extended depending on popularity:
For example:
.lang-en .format-socialwall .tl-comments:before { content: "\f0e6 Comments"; }
.lang-fr .format-socialwall .tl-comments:before { content: "\f0e6 commentaires"; }
.lang-it .format-socialwall .tl-comments:before { content: "\f0e6 commenti"; }
.lang-es .format-socialwall .tl-comments:before { content: "\f0e6 Comentarios"; }

This then would allow any translation to be dynamically added as and when a user selected a specific language. Such is the beauty of CSS.

Peace be with you...
Mary

**Comment by kennibc** [comment]
Thanks Mary.  Your last comment was much nicer than calling me a fool and telling me to read proper coding tutorials.  I might not be at your skill level but I hope my contribution to the Moodle community is of value.  
Sometimes these things are over my head and it is leaders like yourself who can either help or discourage future contributions.   
This is no walk in the park trying to help and answer every question.  It isn't even part of my job, but we love Moodle.  I thought our theme was unique enough that others might want to give it a try.  I am not an expert but projects like this help build my very basic skills.

Thank you.  I do appreciate your solution in this matter.

**Comment by kennibc** [comment]
Thanks Mary.  
Maybe I was over-reacting to your all caps response.  I do want to do things the right way but some of this is beyond my area of expertise.  This can lead to frustration because I do want to fix the issue but don't know how.  
Nobody likes to look foolish. Your last response was much more productive.  Thank you I appreciate your help in this matter.  
I wish I knew as much as you about theming.

**Comment by lazydaisy** [comment]
The mystique that surrounds me on the Moodle Themes' Forum is akin to a legend. In real life I am nothing like I am on the web. Yes I can do a bit of coding, and yes I taught myself CSS and PHP, but I know precious little about how Moodle is actually put together. I came on the Moodle scene quite by chance as it happens at a time when Moodle 2.0 was being talked about circa 2008/9. By the year 2010 I was an active member of the forum and picked up lots of tips from people such as Frank Ralf who was one of the main contributors of the Themes forum at that time. And so I do owe a lot to people like Frank, who took time to explain things. I only know what I know now because I stuck at it, and questioned why something was done the way it was. When you have been answering questions and fixing 'Moodle Bugs' as long as I have then you too would know all there is to know about themes!
Cheers
Mary

**Comment by kennibc** [comment]
Thank to Mary I have a working solution in regards to the :before CSS styling in which it brings in text.  Below is a model for how you can change the evolved.css file beginning around line 744.  I just did the english language but will add the other most popular languages in the next release.

/* Socialwall Language Strings based on popular languages.  These are only visible when you use the Socialwall Course format plugin. */
.lang-en.format-socialwall ul.section.tl-postattachment:before { content: "\f0c6  Attachments"; }
.lang-en.format-socialwall .tl-comments:before { content: "\f0e6  Comments"; }
.lang-en.format-socialwall .tl-posttext:before{ content: "\f0e5  Message"; }
.lang-en.format-socialwall .tl-post:before{ content: "\f086  Post" }

.format-socialwall ul.section.tl-postattachment:before {
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  margin-left:-15px;
  padding-bottom: 4px;
  border-bottom:2px solid #ccc;
}
.format-socialwall .tl-comments:before {
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  padding-bottom: 4px;
  width:100%;
  text-align: center;
}

.format-socialwall .tl-posttext:before{
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 16px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  margin-bottom: 7px;
  padding-bottom: 4px;
  border-bottom:2px solid #ccc;
  width:100%;
  text-align: center;
}

.format-socialwall .tl-post:before{
  color:#A83116;
  line-height: 20px;
  horizontal-aling: ;
  display: inline-block;
  font: 18px/1 FontAwesome;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0);
  padding-bottom: 4px;
  padding-left:15px;
  text-align: center;
}

**Comment by lazydaisy** [comment]
Chris,
You can go one or two steps further from here. 
1. Divide the four CSS groups into common and unique CSS sub groups. Meaning all the styles that are the same, such as color, font-family, line-height etc where styles relate on a one to many basis, and unique where styles relate on a one to one basis.
2. Create a setting that enables the Admin to choose a color for the icon and title.

**Comment by kennibc** [comment]
I am thinking of using a separate CSS sheet just for socialwall.  Then it can be a little cleaner.  
Another idea I had was to offer maybe 3 unique styles that the admin could pick from to give it a unique look.  This is why I was thinking of separating out the CSS to a new file.  In the admin settings for the theme you could pick from a couple Socialwall Styles in the backend.  

I like the idea of adding in the color on the settings page too.  I might have to implement this.

I could easily see this growing into a new page in the Theme admin area just for Socialwall.

PS.  I just posted the fixes here on github.  Try it out and let me know if you see any issues.  I also fixed some language strings on the custom login page too.  These are in the language file as I could load them in the PHP page.

**Comment by germanvaleroelizondo** [comment]
I can confirm that the new version works beautifully with 18 new language strings available for translation/customization. Keep on the good work +1

**Comment by kennibc** [comment]
Thank You!  I am also adding a new page for the socialwall course format in which you can pick the background colors of the Add Post Area, timeline post, message area, comment area, attachment area, and a color picker for those darn icons and text that got this whole thing started. 
 This should provide a very nice and customized experience if you use Socialwall.  I will be pushing this up to Moodle.org shortly.  I just want to test a few items.

**Comment by lazydaisy** [comment]
Hello again Chris, 
I am not sure why "horizontal-aling:" is in the CSS,
indeed I am not even sure it exists?
Sounds like it should be...
horizontal-align: ;
similar to vertical-align: ;
but I cant find any reference.
Best remove it as it isn't doing anything!

**Comment by kennibc** [comment]
Thanks Mary on that find!  Also, I had the idea that a better approach might be to use a text box to allow users to put in their own timeline labels.  This might be better than doing translations as each person could type in their own labels.  It would work just like a css color picker but with text.  

I am going to give it a try.

**Comment by kennibc** [comment]
German and Mary,
If you take a look at the current version here on github, I did away with the translation.  You can now change the Socialwall CSS labels from the new Socialwall options page on the Evolve-D Theme settings.  This will allow everyone to easily translate to their own language and not have to touch the code.  

Thank you all for this has been a very good step forward for the development of this theme.     

Let me know what you think of this latest update.

**Comment by lazydaisy** [comment]
Ah but what happens if the site is multi cultural?

**Comment by kennibc** [comment]
ugh... I didn't think that through!

**Comment by kennibc** [comment]
So I think I have a nice balance for those who only use one language and those with multi language sites.  You can change the default language labels for Socialwall in the Socialwall Theme admin page which is ideal for single language sites.  At the bottom of that page I include a customcss-like box where the site admin can use the examples provided to add translations as needed.  This way the user can change the text for all language strings if they decide to use a word other than Post, Message, Comment, or Attachment.

**Comment by germanvaleroelizondo** [comment]
That seems to be an excellent solution.
Congratulations. 
I will update soon the Moodle Docs page at https://docs.moodle.org/29/en/evolve-D_theme to reflect these changes.

**Comment by kennibc** [comment]
Great!  Thanks so much for your help.  This ultimately resulted in a big improvement for this theme.

**Comment by germanvaleroelizondo** [comment]
Hi, 
I finished updating the page at https://docs.moodle.org/29/en/Evolve-D_theme .

Could you please update the page at https://moodle.org/plugins/view/theme_evolved,  so that the 'Useful links' area link to 'More documentation on this plugin' points to this Moodle Docs page, so that Moodle users of other languages (eg, Spanish) can link to translated Moodle Docs pages ? Please feel free to change/add/remove whatever you might think this page might need. I will soon update the Spanish translation page and the Moodle 2.8 Docs page.

Thanks a lot for the many improvements recently made to this great and highly successful plugin :+1:

**Comment by kennibc** [comment]
I was one step ahead of you.  Did it like 10 minutes ago and I also removed the Google Doc link in the description and replaced it with the page you created and gave you credit.  

Thanks for helping.
