### ISSUE TITLE
Multilang filter not working for Moodle 2.8 theme

### ISSUE THREAD

**Issue by federicama** [kennibc/moodle-theme_evolved#11]
Dear,

Thanks for sharing this theme, it is very nice and clean. I am testing it for my Moodle, at the moment I am testing in Moodle 2.8.5 but we're upgading to Moodle with 2.9 version soon.

In the platform there are users from different nationalities and I use the multilang filter to customize the messages Now that I am testing it with your theme it looks not working. 

I checked in the filters setting and it is on.
Am I doing something wrong?

Thanks!

**Comment by kennibc** [comment]
I would try another theme just to make sure your plugin is working first.  Then try EvolveD. I guess I would need more information.  What exactly isn't working?  Please be more specific.  A screenshot might be useful too.

**Comment by federicama** [comment]
Here is the screenshot of the marketing spots we have now in our production environment.
As you can see there is this "< span multilang >" filter in the html code. This is a filter, not a plugin. You can find it in WWW.YOUR MOODLE.Xy/admin/filters.php
So far it works with Essential theme.

![mutilang](https://cloud.githubusercontent.com/assets/11957594/9008316/a859e240-3799-11e5-9651-914c45efdf3b.jpg)

**Comment by kennibc** [comment]
It could be that the filter just isn't being processed by the Marketing Spots.  If you put the same code elsewhere in the site does it work properly with the Evolve-D theme?

**Comment by federicama** [comment]
Yes, you are right. ;)
The problem is mainly with the marketing spots. Either in the contents either in the headings.

Do you think can it be fixed?

**Comment by kennibc** [comment]
Yes.  But unfortunately I do not have the time right now.  I would have to dig in and see how and where the language filter is applied and then see if I can set the conditions right for the marketing boxes to be included with the Moodle filters.  
If someone knows how to make this happen then I would be more than happy to have it included moving forward.

**Comment by kennibc** [comment]
Can you copy/paste your code used in the marketing spots?  I want to see if a simple solution exists and will need it for testing.

**Comment by federicama** [comment]
Thanks! Hope it will happen soon, I like your theme but I fear I cannot use it with no multilang. 

I tested different contents the code is:
<span lang="en" class="multilang">english.</span><span lang="fr" class="multilang">french.</span><span lang="pt_br" class="multilang">portuguese</span><span lang="es" class="multilang">spanish</span><span lang="tr" class="multilang">turkish</span><span lang="vi" class="multilang">vietnamese</span><span lang="de" class="multilang">german</span><span lang="id" class="multilang">indonesian</span><span lang="ja" class="multilang">japanese</span>

**Comment by federicama** [comment]
< span lang="en" class="multilang">Here all users can browse and download resources.< /span >< span lang="fr" class="multilang">Tous les utilisateurs peuvent parcourir cette bibliothèque et télécharger des ressources.< /span>< span lang="pt_br" class="multilang">Aqui todos os usuários podem procurar e baixar recursos.< /span>< span lang="es" class="multilang">Aquí, todos los usuarios pueden buscar y descargar recursos.< /span>< span lang="tr" class="multilang">Burada, tüm kullanıcılar kaynakları tarayabilir ve indirebilir.< /span>< span lang="vi" class="multilang">Tại đây tất cả người dùng có thể duyệt và tải tài liệu.</span>< span lang="de" class="multilang">Hier können alle Benutzer recherchieren und Quellen herunterladen.< /span>< span lang="id" class="multilang">Di sini semua pengguna dapat menelusuri dan mengunduh sumber informasi.< /span>< span lang="zh_tw" class="multilang">所有的用户可在此浏览和下载资源。< /span>< span lang="zh_cn" class="multilang">這裡是所有使用者可以瀏覽以及下載資源。< /span>< span lang="ja" class="multilang">ここでは全てのユーザーが資料を閲覧し、　ダウンロードすることができます。< /span>
<br>Without spaces! Sorry for the first message!

**Comment by kennibc** [comment]
Looking into it.  Thanks.

**Comment by kennibc** [comment]
This might be able to make it into a Moodle 3.0 version of this theme but unless someone wants to help I do not have the time to make it so that the language filter can work in the Marketing Spots.  I am not seeing an easy fix but I am sure someone that has better coding might be able to offer a fix and I would gladly put it into the theme.
