### ISSUE TITLE
hard-wired English strings in fpcustom.php file in evolve-D theme

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kennibc/moodle-theme_evolved#12]
Hi,
Sorry to bother you again, but when using the custom login page there are a few hard-wired English language strings used by the  fpcustom.php file: username, password, forgot ?, Log In

![evolved theme hard-wired english language strings](https://cloud.githubusercontent.com/assets/2671923/9027257/cd949f66-3913-11e5-9963-1227be72d1fa.png)

I hope this php file is easier to change the hard-wired strings into variables that can be translated by AMOS.

This plugin is extremely popular and many Moodle users of languages other than English would benefit if it was possible to translate all the English language strings.

Thanks in advance for your help.

**Comment by kennibc** [comment]
@germanvaleroelizondo Thank you for pointing this out too.  I do believe since it is a PHP file I can use language strings.  I will be sure to include this in the next version.  

Some of this is beyond my expertise but with a little help we can get this theme up to standards for everyone and all the various languages.

**Comment by kennibc** [comment]
In your language file add this:
//Custom Login Page 
$string['lginuser'] = 'username';
$string['lginpass'] = 'password';
$string['lginforgot'] = 'forgot ?';
$string['lginlogin'] = 'Log In';
and translate as needed.

In the layout/includes/fpcustom.php replace the entire < section > area with this:
<section>
    <div class="wrap">
		<div class="avatarlogin">
        <img src="<?php echo $OUTPUT->pix_url('avatar', 'theme'); ?>" alt="Login" />
	   </div>
        <form action="<?php echo new moodle_url('/login/index.php'); ?>" method="post" id="login"  >
		<input type="text" name="username" placeholder="<?php echo get_string('lginuser' , 'theme_evolved'); ?>" required>
		<div class="bar">
			<i></i>
	   </div>
		<input type="password" name="password" placeholder="<?php echo get_string('lginpass' , 'theme_evolved'); ?>" required>
        <a href="<?php echo new moodle_url('/login/forgot_password.php'); ?>" class="forgot_link"><?php echo get_string('lginforgot' , 'theme_evolved'); ?></a>
		<button><?php echo get_string('lginlogin' , 'theme_evolved'); ?></button>
        </form>
    </div>
</section>

This will allow translation on the frontpage.  I will include this in the next release.  Thank you so much.  I am learning from all of this and trying to be better at supporting different languages.

**Comment by kennibc** [comment]
Opps...  It cut out my code.  I will make the changes and you can download them soon.
