### ISSUE TITLE
Social wall unable to use

### ISSUE THREAD

**Issue by methodlabs** [kennibc/moodle-theme_evolved#13]
I created a new course for social wall and I am unable to post ot add anything beyond what can be seen on the screenshot attached.
The Administration block also says Activity chooser on but I don't find activity chooser.
Have I missed something?
![screenshot from 2015-08-06 16 41 53](https://cloud.githubusercontent.com/assets/13677076/9110376/d6ff4124-3c5a-11e5-9b18-1368e87bd018.png)

**Comment by kennibc** [comment]
Does it do this with new courses or just this one course?

**Comment by methodlabs** [comment]
I added 2 new courses in social format and topics format now. I stil dont see the activity chooser.

**Comment by kennibc** [comment]
Can you delete the courses and completely uninstall-reinstall the socialwall plugin?   I am thinking it didn't fully install.  The other thing to do is upload the files via FTP to ensure they are all present. 

The other thing I see is you have some type of chatroom and who's online at the bottom of the page.  Is that a Moodle Plugin?  I wonder if that is interfering.

**Comment by methodlabs** [comment]
the virtual chat was installed by the moodle host just now. I had the
problem before as well. will uninstall that too and see.
thanks for the support
guna

**Comment by kennibc** [comment]
Also, what version of Moodle are you using?

**Comment by methodlabs** [comment]
2.9.1 moodle version

**Comment by methodlabs** [comment]
I am trying to uninstall Socialwall plugin. I did not see a Uninstall link
in the plugins list. I could only Uninstall Block Alerts. Shouls I delete
the folder from the server?
guna

**Comment by kennibc** [comment]
You have to uninstall the filters and other elements first.  Then you will see the uninstall for the Socialwall itself.  As you can see the filter and block are required so they have to be uninstalled first.  Then the actual course format.  

![moodle 2 9 dev administration plugins plugins overview](https://cloud.githubusercontent.com/assets/1692748/9111865/c55035ce-3c18-11e5-825c-5b48ff633ba8.png)

**Comment by methodlabs** [comment]
I could only uninstall block_alerts
filter_urlresource shows dependency on local_filterurlresbak and
local_filterresbak shows dependency filter_urlresource
Mutual dependency?

**Comment by kennibc** [comment]
That might be the case.  I would just manually remove them and do the uninstall for socialwall.

**Comment by methodlabs** [comment]
i guess by manual remove you mean delete with ftp. I will try and revert.
guna

**Comment by methodlabs** [comment]
sorry to bother you with this again.
I managed to remove the 2 local pugins and updated plugins database after errors showed up.
I am unable to find where the socialwall plugin is located on server as there is no directory visible in \httpdocs folder. 
Also there seems to be another dependency of Topics format (attached)
![screenshot from 2015-08-06 19 38 35](https://cloud.githubusercontent.com/assets/13677076/9113681/8bef77da-3c73-11e5-890b-9e77699d04b2.png)

**Comment by kennibc** [comment]
Yes.  It does require topics format but do not delete that!   The socialwall is located in root/course/format/socialwall

**Comment by methodlabs** [comment]
deleted it. Will reinstall all 4 plugins back. Is the order of installing
important?

**Comment by kennibc** [comment]
You can install just the socialwall and Alert block to do testing.  I always install the socialwall first, then the other plugins.

**Comment by methodlabs** [comment]
1. I uninstalled all 4 plugins manually
2. Reinstalled Socialwall and block_alerts
3. created a new course
4. opened the course and turned editing on
Same problem (see attached image)
guess socialwall is not for me unless I downgrade to moodle 2.8
will try that on another domain later with 2.8  
guna

**Comment by methodlabs** [comment]
just a question.
Does evolveD or Socialwall use JQuery?
If so your intuition is right. It is the VM chat plugin that interferes with the social wall on my installation. I had merely disabled it earlier, now I will remove it completely. VM chat is developed and maintained by my moodle host, so I had it since the time they gave me a free hosting space for trial. Will try Social wall again and post to complete this issue.

**Comment by kennibc** [comment]
I believe the theme and socialwall use Jquery.  I bet if you uninstall it will be fine.  Remember to clear the Moodle cache and browser cache.

**Comment by methodlabs** [comment]
And Socialwall works.
the plugin VM chat that has a JQuery problem was indeed blocking it.
Thank you for all the time.
The issue I raised is resolved.

**Comment by methodlabs** [comment]
The mutual dependency between local_filterurlresbak and filter_urlresource
still continues.
I guess that becomes an issue only while uninstalling these plugins.

**Comment by kennibc** [comment]
We are close to a next release with some brand new features and I will work
with the developer to make sure it is not a dependency "loop".

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
*Michigan Moodle User group
<https://www.facebook.com/groups/819830188053375/> (Facebook)*
http://iblog.dearbornschools.org/technology
http://webmaster.dearbornschools.org

**Comment by methodlabs** [comment]
Just 2 unrelated last questions.
I am marketing my new course and chose not have a site outside moodle for
that.
Is there a way to have the social wall on the home page?

Is it possible to open up the home page to public access till we promote
our course and get students?

I think it is not possible but before I try, your opinion can help.

Guna

**Comment by kennibc** [comment]
Socialwall is a course format so it must be in a course and not the homepage.  

Evolve-D allows you to turn the custom homepage on or off in the Theme Admin > Frontpage Options.  If you turn it off the Moodle frontpage will look and feel just like normal.  Then once you get your users you can turn on the homepage.  

A better solution would be to use Wordpress for all of your PR and overview of the courses and once they are ready to enroll you send them over to your Moodle site to sign up.

**Comment by methodlabs** [comment]
Thank you Chris. I will be closely following the developments on EvolveD &
Socialwall.
Guna

**Comment by kennibc** [comment]
Be sure to heart the plugins on Moodle.org's plugin directory.  Thanks Guna!

**Comment by methodlabs** [comment]
closing the issue as it has been resolved.
