### ISSUE TITLE
How to remove search box from home page

### ISSUE THREAD

**Issue by janetfearns** [kennibc/moodle-theme_evolved#14]
Hi
I am developing safety courses for our institutes staff and I have used your wonderful evolve - d theme. As we only have two course for this training (linked from the marketing spots), I would like to remove the course search box from the front page. Could you tell me how I can do this? Thanks
![evolved](https://cloud.githubusercontent.com/assets/13862971/9348593/df5d7e68-467c-11e5-85e5-fd2d31b16b72.JPG)

**Comment by kennibc** [comment]
Remove this from fpcustom_lgin.php  this is the search form.
https://github.com/kennibc/moodle-theme_evolved/blob/master/layout/includes/fpcustom_lgin.php#L134

**Comment by kennibc** [comment]
Be sure to remove the form within the DIV I mentioned above.
