### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by jimmertek** [kennibc/moodle-theme_evolved#17]
Hi, we're trying evolve and really like the background image. We've got it set to default styling and to fix width / stay in position. However, every page load it pulls down the image (300kb). Is there a reason why it is not being cached by our clients? The constant download/render takes away from the slick presentation.

**Comment by kennibc** [comment]
Not quite sure why it wouldn't cache.  It is just css like any other image.  We used evolve-D last year and it was great.  This year we are using Pioneer.
