### ISSUE TITLE
Gradebook overflow to blocks

### ISSUE THREAD

**Issue by robinleung** [kennibc/moodle-theme_evolved#3]
There's a gradebook issue where the grader report is overflowed to cover blocks. 
![gradebook-bug](https://cloud.githubusercontent.com/assets/8377859/7034887/a69a775a-dd38-11e4-91e0-6ac3230243e0.jpg)

**Comment by kennibc** [comment]
This is due to Moodle 2.8's full screen gradebook.  I just noticed this over the Easter break and I am working on a fix where the gradebook would switch the location of the blocks to be on the left and the gradebook would flow to the right and eliminate the overlapping.  

Should be done soon.

**Comment by robinleung** [comment]
Thanks Chris. Appreciate it if you could let me know when a fix is in place. For now, I was able to move the blocks to the bottom of the gradebook, which is as far as I got.

**Comment by kennibc** [comment]
http://iblog.dearbornschools.org/webmaster/wp-content/uploads/sites/3/2014/02/evolved_m28_2.0.1.zip  Try this one on a test server.  Seems to work for me on my dev site.

**Comment by robinleung** [comment]
Thanks Chris. This works! 
Now, I just have to see what's changed in the code to implement it on my version.

**Comment by kennibc** [comment]
You could just FTP it up to your site and overwrite what is there currently.  Be sure to purge cache.  

It will be in the next update when I put it on the repository for Moodle.org

**Comment by robinleung** [comment]
Thanks again, Chris. I'm better off looking for the code because I've made significant changes to your theme to better fits our institution for higher ed.

**Comment by kennibc** [comment]
Glad you like the theme!  Care to share your site?  I love to see the creative stuff people do with it.

**Comment by robinleung** [comment]
The site is not live yet. We're still in the midst of fine-tuning. Once it's live, I'll be glad to share it. What's your email?

**Comment by kennibc** [comment]
kennibc@dearbornschools.org  Thanks!

**Comment by kennibc** [comment]
Anything that can be shared I would be happy to take a look and include it with a future update to the theme.

**Comment by robinleung** [comment]
Hi Chris,

I found the change. How did you get region-main to get the class to "pull-right"?

**Comment by kennibc** [comment]
In the template file I believe.  I applied pull-right.  Columns2.php   
<section id="region-main" class="span9<?php if ($left) { echo ' pull-right'; } ?>">

**Comment by kennibc** [comment]
<code><section id="region-main" class="span9<?php if ($left) { echo ' pull-right'; } ?>"></code>
