### ISSUE TITLE
Feature enhancement: auto dropdown of the usermenu

### ISSUE THREAD

**Issue by robinleung** [kennibc/moodle-theme_evolved#4]
I've looked all last week and I can't seem to figure out how to call for the usermenu to auto drop down when hovering over it. If you can shed me some light that would be great. I was able to get the custom menus to auto drop down using CSS. But for some reason, the usermenu will not behave the same way. 

Thanks.

**Comment by kennibc** [comment]
On Moodle 2.8 that is a feature of Moodle and not the theme - to the best of my knowledge.  Drop down on hover is not on the map in terms of features.
