### ISSUE TITLE
Screen blank after installation - Zero Access

### ISSUE THREAD

**Issue by dantyas** [kennibc/moodle-theme_evolved#6]
After installing the theme and activating there is no option to login or change any settings, please see attached images. 
![moodle](https://cloud.githubusercontent.com/assets/13313684/8648609/e6597798-2959-11e5-9da3-0d21abc6b05c.PNG)

**Comment by kennibc** [comment]
Please be sure that you are using the proper version of the theme for your Moodle install.  There are two.  One is for Moodle 2.7 and one is for 2.8 and newer.  Current downloads are on Moodle.org.

**Comment by dantyas** [comment]
Hello

Thank you for your response I will check now

Kind Regards

Dan

*Daniel Tyas*

Sales, Education and Digital Outreach Manager
01484666261



Follow our latest news on Twitter!
<https://twitter.com/DEMANDCharity?lang=en-gb>







*www.demand.org.uk <http://www.demand.org.uk/index.php/about-us/demand/>*

Onyx House, 303 Newmill Road, Brockholes, Holmfirth, HD9 7AL

The Old Chapel, Mallard Road, Abbots Langley, WD5 0GQ

*Registered under the Charities Act No.1008128*

*Company Limited by Guarantee Registered in England No.2671913*

This E-mail may contain copyright protected, confidential and/or legally
privileged material.

If you have received this message in error, please notify us and remove it
from your system.

**Comment by dantyas** [comment]
Hello

I have checked and it is the latest version that I have installed

Kind Regards

Dan

*Daniel Tyas*

Sales, Education and Digital Outreach Manager
01484666261



Follow our latest news on Twitter!
<https://twitter.com/DEMANDCharity?lang=en-gb>







*www.demand.org.uk <http://www.demand.org.uk/index.php/about-us/demand/>*

Onyx House, 303 Newmill Road, Brockholes, Holmfirth, HD9 7AL

The Old Chapel, Mallard Road, Abbots Langley, WD5 0GQ

*Registered under the Charities Act No.1008128*

*Company Limited by Guarantee Registered in England No.2671913*

This E-mail may contain copyright protected, confidential and/or legally
privileged material.

If you have received this message in error, please notify us and remove it
from your system.

**Comment by kennibc** [comment]
The only time I've seen this is when you have Moodle 2.7 and you use the version of my theme which is designed for Moodle 2.8 or newer.  There is a specific version for Moodle 2.7 and the 2.8 one is not compatible.  

You haven't listed any other important details other than your problem so it is hard to help you.  Describing your server and Moodle setup would be a big help.

**Comment by dantyas** [comment]
My apologies so I downloaded the file theme_evolved_moodle29_2015050500,
installed it to the theme folder and activate it in moodle.

The moodle installation is in a sub-directory on a hosting package from
heartinternet.

I can provide any other information you require


*Daniel Tyas*

Sales, Education and Digital Outreach Manager
01484666261



Follow our latest news on Twitter!
<https://twitter.com/DEMANDCharity?lang=en-gb>







*www.demand.org.uk <http://www.demand.org.uk/index.php/about-us/demand/>*

Onyx House, 303 Newmill Road, Brockholes, Holmfirth, HD9 7AL

The Old Chapel, Mallard Road, Abbots Langley, WD5 0GQ

*Registered under the Charities Act No.1008128*

*Company Limited by Guarantee Registered in England No.2671913*

This E-mail may contain copyright protected, confidential and/or legally
privileged material.

If you have received this message in error, please notify us and remove it
from your system.

**Comment by kennibc** [comment]
What version of Moodle do you have installed?

**Comment by dantyas** [comment]
sorry an obvious bit of information to miss.. 2.9

*Daniel Tyas*

Sales, Education and Digital Outreach Manager
01484666261



Follow our latest news on Twitter!
<https://twitter.com/DEMANDCharity?lang=en-gb>







*www.demand.org.uk <http://www.demand.org.uk/index.php/about-us/demand/>*

Onyx House, 303 Newmill Road, Brockholes, Holmfirth, HD9 7AL

The Old Chapel, Mallard Road, Abbots Langley, WD5 0GQ

*Registered under the Charities Act No.1008128*

*Company Limited by Guarantee Registered in England No.2671913*

This E-mail may contain copyright protected, confidential and/or legally
privileged material.

If you have received this message in error, please notify us and remove it
from your system.

**Comment by kennibc** [comment]
I am thinking you should do the following:
1. Delete entire theme folder and switch to Moodle's default theme.
2. Clear Moodle's cache.  
3. Reinstall the theme.

Sorry, the only time I have seen this issue is when using Moodle 2.7 and trying to install the wrong version of the theme.

**Comment by dantyas** [comment]
Hi Chris

Thank you for your help, I re-installed moodle using ftp instead of the
hosts built in 'app installer' and the theme installed without a problem.

If I can I do however have one remaining question, how do I add a 'register
here' link to the login front page as I would like users to be able to
register themselves.

Hope that makes sense

*Daniel Tyas*

Sales, Education and Digital Outreach Manager
01484666261



Follow our latest news on Twitter!
<https://twitter.com/DEMANDCharity?lang=en-gb>







*www.demand.org.uk <http://www.demand.org.uk/index.php/about-us/demand/>*

Onyx House, 303 Newmill Road, Brockholes, Holmfirth, HD9 7AL

The Old Chapel, Mallard Road, Abbots Langley, WD5 0GQ

*Registered under the Charities Act No.1008128*

*Company Limited by Guarantee Registered in England No.2671913*

This E-mail may contain copyright protected, confidential and/or legally
privileged material.

If you have received this message in error, please notify us and remove it
from your system.
