### ISSUE TITLE
Empty link in Marketing spot

### ISSUE THREAD

**Issue by beloit-rexj** [kennibc/moodle-theme_evolved#8]
If one of the marketing spots does not include a link, then the red button background appears in the lower-right corner of the marketing spot as a small rounded rectangle.
![mdl 29 evolved marketing spot link](https://cloud.githubusercontent.com/assets/9689055/8703855/1ee04934-2ae5-11e5-9cc7-65d181707b8e.png)

It is preferable that if there is nothing entered in the link text/URL that this button does not appear at all.

**Comment by kennibc** [comment]
If you have a fix please send it my way.  I am swamped right now and will not have a chance to look at this.  It functions as intended and the use-case was to include a link.  I can see people not wanting to add a link so I will keep this on the radar to take a look at in the future.
